# Generated by Django 3.1 on 2020-08-19 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='students.gender', null=True),
            preserve_default=False,
        ),
    ]
