# Generated by Django 3.1 on 2020-08-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(max_length=30)),
                ('post_by', models.TextField(max_length=40)),
                ('location', models.TextField(max_length=40)),
            ],
        ),
    ]
